name: Local Assistant
version: 1.0.0
schema: v1
models:
  - uses: anthropic/claude-3-7-sonnet
    with:
      ANTHROPIC_API_KEY: 
  - uses: anthropic/claude-4-sonnet
    with:
      ANTHROPIC_API_KEY: 
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
